-- メインテーブル作成
CREATE TABLE IF NOT EXISTS packets
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
    timestamp   TIMESTAMPTZ NOT NULL,
    node_id     SMALLINT    NOT NULL,
    src_mac     MACADDR     NOT NULL,
    dst_mac     MACADDR     NOT NULL,
    ether_type  INTEGER     NOT NULL,
    ip_protocol INTEGER     NOT NULL,
    src_ip      INET        NOT NULL,
    dst_ip      INET        NOT NULL,
    src_port    INTEGER     NOT NULL,
    dst_port    INTEGER     NOT NULL,
    raw_packet  BYTEA       NOT NULL,
    CONSTRAINT packets_pkey PRIMARY KEY (id, timestamp)
);

CREATE TABLE processed_packets (
    packet_id BIGINT,
    node_id SMALLINT,
    processed_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (packet_id, node_id)
);

-- ハイパーテーブルへの変換
SELECT create_hypertable('packets', 'timestamp', chunk_time_interval => INTERVAL '1 hour');

-- 主要な検索パターン用のインデックス
CREATE INDEX idx_packets_node_timestamp_included ON packets (node_id, timestamp DESC) INCLUDE (raw_packet);

-- 圧縮設定（オプション）
ALTER TABLE packets SET (timescaledb.compress, timescaledb.compress_segmentby = 'node_id', timescaledb.compress_orderby = 'timestamp DESC');

-- 自動圧縮ポリシーの設定（オプション）
SELECT add_compression_policy('packets', INTERVAL '7 days');

-- 最後にtimestampのみのインデックスを削除
DROP INDEX IF EXISTS packets_timestamp_idx;
